"use client";

import { useEffect, useState } from "react";
import { usePathname, useRouter } from "next/navigation";
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUpRight, Check, Menu, Minus, Plus, ShoppingBag, X } from "lucide-react";

type Lang = "fr" | "en";
const A = (path:string) => `${process.env.NEXT_PUBLIC_BASE_PATH ?? ""}${path}`;
const I = {
  hero:A("/images/crowd-energy-02.webp"), performance:A("/images/performance.webp"), signage:A("/images/vibes-signage.webp"), foam:A("/images/foam-party.webp"),
  portraitWhite:A("/images/guest-portrait-white.webp"), bottles:A("/images/belaire-table.webp"), portraitBlack:A("/images/guest-portrait-black.webp"),
  toast:A("/images/cocktail-toast.webp"), editorial:A("/images/editorial-portrait.webp"), crowd:A("/images/crowd-energy-01.webp"),
  bartender:A("/images/soma-bar-portrait.webp"), bar:A("/images/soma-bar-service.webp"), fashionClose:A("/images/fashion-portrait-close.webp"), fashionFull:A("/images/fashion-portrait-full.webp")
};
const C = {
  fr:{nav:{home:"Accueil",about:"À propos",services:"Services",univers:"Univers",realisations:"Réalisations",galerie:"Galerie",blog:"Journal",boutique:"Boutique",faq:"FAQ",contact:"Contact"},book:"Réserver",quote:"Demander un devis",discover:"Découvrir SŌMA",view:"Voir le projet",more:"En savoir plus",heroA:"Transformer chaque idée",heroB:"en expérience.",heroText:"SŌMA imagine, conçoit et produit des expériences élégantes, immersives et profondément personnalisées.",manifesto:"Nous ne créons pas simplement des événements.",manifesto2:"Nous imaginons des expériences dont on se souvient.",founder:"Fondatrice & Directrice Créative",worlds:"Les univers SŌMA",services:"Ce que nous faisons",projects:"Sélection de réalisations",journal:"Le journal",finalA:"Une idée en tête ?",finalB:"Transformons-la en expérience.",talk:"Parler à SŌMA",newsletter:"Inspiration, coulisses et prochaines expériences.",subscribe:"S’inscrire"},
  en:{nav:{home:"Home",about:"About",services:"Services",univers:"Worlds",realisations:"Work",galerie:"Gallery",blog:"Journal",boutique:"Shop",faq:"FAQ",contact:"Contact"},book:"Book",quote:"Request a proposal",discover:"Discover SŌMA",view:"View project",more:"Learn more",heroA:"Turning every idea",heroB:"into an experience.",heroText:"SŌMA imagines, designs and produces elegant, immersive and deeply personal experiences.",manifesto:"We do not simply create events.",manifesto2:"We imagine experiences worth remembering.",founder:"Founder & Creative Director",worlds:"The SŌMA worlds",services:"What we do",projects:"Selected work",journal:"The journal",finalA:"Have an idea in mind?",finalB:"Let’s turn it into an experience.",talk:"Talk to SŌMA",newsletter:"Inspiration, behind the scenes and upcoming experiences.",subscribe:"Subscribe"}
};
const worlds=[
  {slug:"soma-experiences",name:"SŌMA Experiences",fr:"Événementiel & direction créative",en:"Events & creative direction",image:I.hero,color:"#b69a63"},
  {slug:"vibes-by-soma",name:"VIBES by SŌMA",fr:"Concepts signature & lifestyle",en:"Signature concepts & lifestyle",image:I.foam,color:"#d56c32"},
  {slug:"soma-bar",name:"SŌMA Bar",fr:"Cocktails & hospitalité",en:"Cocktails & hospitality",image:I.bar,color:"#173c34"},
  {slug:"soft-glow-shoot",name:"Soft Glow Shoot",fr:"Photographie & image",en:"Photography & image",image:I.fashionClose,color:"#9d6e70"},
  {slug:"bonnets-land",name:"Bonnets Land",fr:"Objets & collections",en:"Objects & collections",image:I.portraitBlack,color:"#4c5464"}
];
const services={fr:["Conception événementielle","Direction artistique","Organisation & coordination","Production événementielle","Communication & contenu","Expériences bar","Photographie","Concepts personnalisés"],en:["Event design","Creative direction","Planning & coordination","Event production","Communication & content","Bar experiences","Photography","Bespoke concepts"]};
const projects=[{name:"Nomo Vibes",cat:"VIBES · Lifestyle",year:"2025",image:I.signage},{name:"After Dark",cat:"Expérience musicale",year:"2025",image:I.performance},{name:"Golden Hour",cat:"SŌMA Bar",year:"2025",image:I.bartender},{name:"Soft Glow 01",cat:"Portrait éditorial",year:"2025",image:I.fashionFull}];
const gallery=[I.hero,I.fashionClose,I.bar,I.toast,I.foam,I.portraitWhite,I.crowd,I.bottles,I.fashionFull,I.editorial,I.signage,I.performance,I.portraitBlack,I.bartender];
const posts=[{title:"Recevoir autrement : l’art de créer une atmosphère",cat:"Inspiration",image:I.signage},{title:"Dans les coulisses d’une expérience SŌMA",cat:"Coulisses",image:I.bartender},{title:"Ce que les invités retiennent vraiment",cat:"Conseils",image:I.toast}];

export default function SomaSite(){
  const pathname=usePathname(), router=useRouter(), basePath=process.env.NEXT_PUBLIC_BASE_PATH ?? "", relativePath=basePath&&pathname.startsWith(basePath)?pathname.slice(basePath.length):pathname, parts=relativePath.split("/").filter(Boolean), lang:Lang=parts[0]==="en"?"en":"fr", page=parts[1]||"home", detail=parts[2]||"", t=C[lang];
  const [menu,setMenu]=useState(false),[lightbox,setLightbox]=useState<number|null>(null),[cart,setCart]=useState(0);
  const go=(s:string)=>router.push(`/${lang}${s==="home"?"":`/${s}`}`);
  const switchLang=()=>router.push(`/${lang==="fr"?"en":"fr"}${page==="home"?"":`/${page}${detail?`/${detail}`:""}`}`);
  useEffect(()=>{setMenu(false);window.scrollTo({top:0,behavior:"smooth"})},[pathname]);
  useEffect(()=>{const fn=()=>document.querySelectorAll("[data-reveal]").forEach(el=>{if(el.getBoundingClientRect().top<innerHeight*.92)el.classList.add("is-visible")});fn();addEventListener("scroll",fn,{passive:true});return()=>removeEventListener("scroll",fn)},[pathname]);
  return <div className="site-shell"><Header lang={lang} page={page} menu={menu} setMenu={setMenu} go={go} switchLang={switchLang} cart={cart}/><main>
    {page==="home"&&<Home lang={lang} go={go}/>} {page==="about"&&<About lang={lang} go={go}/>} {page==="services"&&<Services lang={lang} go={go}/>} {page==="univers"&&(detail?<WorldDetail lang={lang} detail={detail} go={go}/>:<Worlds lang={lang} go={go}/>)} {page==="realisations"&&<Projects lang={lang} detail={detail} go={go}/>} {page==="galerie"&&<Gallery lang={lang} open={setLightbox}/>} {page==="blog"&&<Journal lang={lang} detail={detail} go={go}/>} {page==="boutique"&&<Shop lang={lang} cart={cart} setCart={setCart}/>} {page==="faq"&&<Faq lang={lang} go={go}/>} {page==="contact"&&<Contact lang={lang}/>} {page==="reservation"&&<Booking lang={lang}/>} 
  </main><Footer lang={lang} go={go}/><a className="whatsapp" href="https://wa.me/224620327391?text=Bonjour%20S%C5%8CMA%20Experiences%2C%20je%20souhaite%20obtenir%20des%20informations%20concernant%20vos%20services." target="_blank" rel="noreferrer" aria-label="WhatsApp">WA</a>{lightbox!==null&&<Lightbox index={lightbox} setIndex={setLightbox}/>}</div>
}

function Header({lang,page,menu,setMenu,go,switchLang,cart}:{lang:Lang;page:string;menu:boolean;setMenu:(v:boolean)=>void;go:(s:string)=>void;switchLang:()=>void;cart:number}){const t=C[lang],nav=Object.entries(t.nav);return <><header className="header"><button className="brand" onClick={()=>go("home")}><img src={A("/images/logo-horizontal.png")} alt=""/><span>SŌMA</span><small>EXPERIENCES</small></button><nav className="desktop-nav">{nav.slice(0,6).map(([s,n])=><button key={s} className={page===s?"active":""} onClick={()=>go(s)}>{n}</button>)}</nav><div className="header-actions"><button className="lang" onClick={switchLang}>{lang.toUpperCase()} / {lang==="fr"?"EN":"FR"}</button>{cart>0&&<button className="cart" onClick={()=>go("boutique")}><ShoppingBag size={17}/><span>{cart}</span></button>}<button className="btn btn-dark header-cta" onClick={()=>go("reservation")}>{t.book}</button><button className="menu-toggle" onClick={()=>setMenu(true)} aria-label="Menu"><Menu/></button></div></header><div className={`mobile-menu ${menu?"open":""}`}><div className="mobile-menu-top"><span>SŌMA EXPERIENCES</span><button onClick={()=>setMenu(false)}><X/></button></div><nav>{nav.map(([s,n],i)=><button key={s} onClick={()=>go(s)}><small>{String(i+1).padStart(2,"0")}</small>{n}<ArrowUpRight/></button>)}</nav><div className="mobile-menu-foot"><button onClick={switchLang}>FR / EN</button><button onClick={()=>go("reservation")}>{t.book}</button></div></div></>}

function Home({lang,go}:{lang:Lang;go:(s:string)=>void}){const t=C[lang];return <><section className="hero"><img className="hero-image" src={I.hero} alt="Une foule réunie lors d’une expérience SŌMA à Conakry"/><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow">{lang==="fr"?"Maison créative · Conakry, Guinée":"Creative house · Conakry, Guinea"}</p><h1><span>{t.heroA}</span><em>{t.heroB}</em></h1><p className="hero-intro">{t.heroText}</p><div className="hero-actions"><button className="btn btn-light" onClick={()=>go("about")}>{t.discover}</button><button className="text-link light" onClick={()=>go("contact")}>{t.quote}<ArrowUpRight/></button></div></div><div className="hero-index">01 — 05</div><a className="scroll-cue" href="#manifesto"><span>{lang==="fr"?"Défiler":"Scroll"}</span><ArrowDown/></a></section>
  <section id="manifesto" className="manifesto section-pad" data-reveal><p className="section-label">01 · Manifeste</p><div><h2>{t.manifesto}<br/><em>{t.manifesto2}</em></h2><p>{lang==="fr"?"De l’idée au dernier geste, chaque élément est pensé pour former un tout cohérent, sensible et inoubliable.":"From the first idea to the final gesture, every element creates a coherent, meaningful and unforgettable whole."}</p></div></section>
  <section className="founder section-pad" data-reveal><div className="founder-image frame"><img src={I.editorial} alt="Portrait éditorial"/></div><div className="founder-copy"><p className="section-label">02 · Catherine Soumah</p><h2>{t.founder}</h2><p>{lang==="fr"?"Catherine Soumah compose des expériences comme des récits : avec une intention claire, une esthétique juste et une attention absolue portée aux détails.":"Catherine Soumah composes experiences like stories: with clear intent, a discerning eye and absolute attention to detail."}</p><button className="text-link" onClick={()=>go("about")}>{t.more}<ArrowUpRight/></button><div className="founder-note">Conakry<br/>Guinée</div></div></section>
  <section className="worlds-home section-pad" data-reveal><Head label="03 · Maison SŌMA" title={t.worlds}/><div className="world-list">{worlds.map((w,i)=><button className="world-row" key={w.slug} onClick={()=>go(`univers/${w.slug}`)} style={{"--accent":w.color} as React.CSSProperties}><span>{String(i+1).padStart(2,"0")}</span><strong>{w.name}</strong><small>{w[lang]}</small><div className="world-peek"><img src={w.image} alt=""/></div><ArrowUpRight/></button>)}</div></section>
  <section className="services-home section-pad dark" data-reveal><Head label="04 · Expertise" title={t.services} light/><div className="service-grid">{services[lang].map((s,i)=><div key={s}><span>{String(i+1).padStart(2,"0")}</span><h3>{s}</h3></div>)}</div></section>
  <section className="projects-home section-pad" data-reveal><Head label="05 · Portfolio" title={t.projects}/><div className="project-editorial">{projects.map((p,i)=><button className={`project-card card-${i+1}`} onClick={()=>go(`realisations/${slug(p.name)}`)} key={p.name}><div className="project-image"><img src={p.image} alt={p.name}/><span>{t.view}</span></div><div><h3>{p.name}</h3><p>{p.cat} · {p.year}</p></div></button>)}</div></section>
  <section className="method section-pad" data-reveal><p className="section-label">06 · {lang==="fr"?"Notre méthode":"Our method"}</p><div className="method-line">{(lang==="fr"?["Écouter","Imaginer","Concevoir","Produire","Faire vivre"]:["Listen","Imagine","Design","Produce","Bring to life"]).map((m,i)=><div key={m}><span>0{i+1}</span><h3>{m}</h3></div>)}</div></section>
  <section className="numbers section-pad dark" data-reveal><p className="section-label">07 · En mouvement</p><div className="number-grid">{[["40+",lang==="fr"?"expériences imaginées":"experiences imagined"],["06",lang==="fr"?"années de création":"years creating"],["05",lang==="fr"?"univers complémentaires":"connected worlds"],["100%",lang==="fr"?"sur mesure":"bespoke"]].map(x=><div key={x[0]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div></section>
  <section className="testimonial section-pad" data-reveal><p className="section-label">08 · Témoignage</p><blockquote>“{lang==="fr"?"SŌMA a su transformer une intention en une expérience parfaitement orchestrée. Tout semblait naturel, alors que chaque détail avait été pensé.":"SŌMA turned an intention into a beautifully orchestrated experience. Everything felt effortless, yet every detail had been considered."}”</blockquote><cite>— Cliente privée, Conakry</cite></section><JournalStrip lang={lang} go={go}/><FinalCta lang={lang} go={go}/></>}

function Head({label,title,light=false}:{label:string;title:string;light?:boolean}){return <header className={`section-head ${light?"light":""}`}><div><p className="section-label">{label}</p><h2>{title}</h2></div></header>}
function PageHero({number,eyebrow,title,italic,image}:{number:string;eyebrow:string;title:string;italic?:string;image?:string}){return <section className={`page-hero ${image?"with-image":""}`}><div className="page-hero-copy"><p className="section-label">{number} · {eyebrow}</p><h1>{title}{italic&&<> <em>{italic}</em></>}</h1></div>{image&&<div className="page-hero-image"><img src={image} alt=""/></div>}</section>}

function About({lang,go}:{lang:Lang;go:(s:string)=>void}){return <><PageHero number="01" eyebrow={lang==="fr"?"À propos":"About"} title="Catherine" italic="Soumah." image={I.editorial}/><section className="story section-pad" data-reveal><p className="section-label">{lang==="fr"?"La vision":"The vision"}</p><div><h2>{lang==="fr"?"Créer avec intention. Recevoir avec émotion.":"Create with intention. Welcome with emotion."}</h2><p>{lang==="fr"?"Fondatrice de SŌMA Experiences, Catherine Soumah développe une maison créative ancrée à Conakry et ouverte sur le monde. Sa pratique réunit stratégie, sensibilité visuelle et rigueur de production.":"Founder of SŌMA Experiences, Catherine Soumah is building a creative house rooted in Conakry and open to the world."}</p><p>{lang==="fr"?"Un événement réussi ne se résume pas à ce que l’on voit. Il se mesure à ce que l’on ressent et à ce que l’on garde en mémoire.":"A successful event is more than what we see. It lives in what we feel and remember."}</p></div></section><section className="values section-pad dark"><div><p className="section-label">Mission</p><h3>{lang==="fr"?"Transformer chaque idée en une expérience cohérente, esthétique et mémorable.":"Turn every idea into a coherent, beautiful and memorable experience."}</h3></div><div><p className="section-label">Vision</p><h3>{lang==="fr"?"Faire rayonner depuis Conakry une nouvelle manière de créer et de recevoir.":"Build from Conakry a new way to create and host."}</h3></div><div className="value-tags">{["Créativité","Élégance","Confiance","Proximité","Fiabilité","Détail"].map(v=><span key={v}>{v}</span>)}</div></section><section className="ecosystem section-pad"><Head label="L’écosystème" title={lang==="fr"?"Une maison, cinq univers.":"One house, five worlds."}/><div className="world-cards">{worlds.map(w=><button key={w.slug} onClick={()=>go(`univers/${w.slug}`)}><img src={w.image} alt=""/><div><span>{w.name}</span><ArrowUpRight/></div></button>)}</div></section><FinalCta lang={lang} go={go}/></>}

function Services({lang,go}:{lang:Lang;go:(s:string)=>void}){const desc=lang==="fr"?["De la première intuition à un concept clair, singulier et réalisable.","Un langage visuel cohérent pensé pour chaque espace et chaque moment.","Planning, partenaires, logistique et suivi précis de chaque étape.","Une exécution fluide avec des équipes et prestataires coordonnés.","Identité, narration, contenus et amplification autour de l’expérience.","Carte sur mesure, mixologie, équipe bar et mise en scène.","Portraits, reportages et images éditoriales pensées pour durer.","Des formats originaux développés autour de vos objectifs."]:["From an initial intuition to a clear, distinctive and feasible concept.","A coherent visual language designed for every space and moment.","Planning, partners, logistics and precise follow-up at every stage.","Seamless execution with coordinated teams and partners.","Identity, storytelling and content around the experience.","Bespoke menus, mixology, bar team and staging.","Portraits, reports and editorial images made to last.","Original formats developed around your objectives."];return <><PageHero number="01" eyebrow="Services" title={lang==="fr"?"Du concept":"From concept"} italic={lang==="fr"?"à l’émotion.":"to emotion."}/><section className="services-list section-pad">{services[lang].map((s,i)=><article key={s} data-reveal><span>0{i+1}</span><h2>{s}</h2><p>{desc[i]}</p><button onClick={()=>go("contact")}><ArrowUpRight/></button></article>)}</section><section className="process-band"><img src={I.crowd} alt="Une soirée SŌMA"/><div><p className="section-label">{lang==="fr"?"Accompagnement complet":"End-to-end support"}</p><h2>{lang==="fr"?"Idée → Concept → Direction → Organisation → Production → Expérience":"Idea → Concept → Direction → Planning → Production → Experience"}</h2></div></section><FinalCta lang={lang} go={go}/></>}
function Worlds({lang,go}:{lang:Lang;go:(s:string)=>void}){return <><PageHero number="01" eyebrow="Maison SŌMA" title={lang==="fr"?"Cinq univers.":"Five worlds."} italic={lang==="fr"?"Une signature.":"One signature."}/><section className="worlds-grid section-pad">{worlds.map((w,i)=><button key={w.slug} onClick={()=>go(`univers/${w.slug}`)} className="world-panel" style={{"--accent":w.color} as React.CSSProperties}><img src={w.image} alt={w.name}/><div><span>0{i+1}</span><h2>{w.name}</h2><p>{w[lang]}</p><ArrowUpRight/></div></button>)}</section></>}
function WorldDetail({lang,detail,go}:{lang:Lang;detail:string;go:(s:string)=>void}){const w=worlds.find(x=>x.slug===detail)||worlds[0],shots=detail==="soma-bar"?[I.bar,I.bartender,I.bottles]:detail==="soft-glow-shoot"?[I.fashionClose,I.fashionFull,I.portraitWhite]:detail==="vibes-by-soma"?[I.foam,I.signage,I.toast]:[w.image,I.crowd,I.performance];return <div style={{"--world-accent":w.color} as React.CSSProperties}><section className="world-detail-hero"><img src={w.image} alt={w.name}/><div className="hero-shade"/><div><p>Maison SŌMA · {w[lang]}</p><h1>{w.name}</h1></div></section><section className="world-intro section-pad"><p className="section-label">L’univers</p><h2>{lang==="fr"?"Une expression singulière, portée par la même exigence.":"A singular expression, held to the same standard."}</h2><p>{lang==="fr"?"Chaque projet naît d’une intention claire et devient un langage complet : rythme, lumière, matière, service et émotion.":"Every project begins with clear intent and becomes a complete language of rhythm, light, material, service and emotion."}</p></section><section className="world-gallery section-pad">{shots.map((img,i)=><div key={img} className={`world-shot shot-${i}`}><img src={img} alt=""/></div>)}</section><section className="world-next section-pad"><span>{lang==="fr"?"Découvrir un autre univers":"Explore another world"}</span><button onClick={()=>go("univers")}><h2>{lang==="fr"?"Toute la maison SŌMA":"The complete SŌMA house"}</h2><ArrowRight/></button></section></div>}

function Projects({lang,go,detail}:{lang:Lang;go:(s:string)=>void;detail:string}){if(detail){const p=projects.find(x=>slug(x.name)===detail)||projects[0];return <><section className="case-hero"><img src={p.image} alt={p.name}/><div className="hero-shade"/><div><p>{p.cat} · {p.year}</p><h1>{p.name}</h1></div></section><section className="case-intro section-pad"><p className="section-label">Le concept</p><div><h2>{lang==="fr"?"Créer un moment qui change le rythme de la ville.":"Create a moment that shifts the rhythm of the city."}</h2><p>{lang==="fr"?"Une direction créative pensée pour rassembler, surprendre et installer une atmosphère immédiatement reconnaissable.":"A creative direction designed to bring people together, surprise them and establish an instantly recognisable atmosphere."}</p></div></section><section className="case-gallery section-pad"><img src={I.crowd} alt=""/><img src={I.toast} alt=""/><img src={I.performance} alt=""/></section><FinalCta lang={lang} go={go}/></>}return <><PageHero number="01" eyebrow={lang==="fr"?"Réalisations":"Selected work"} title={lang==="fr"?"Des idées qui":"Ideas that"} italic={lang==="fr"?"prennent vie.":"come alive."}/><section className="portfolio-grid section-pad">{projects.map((p,i)=><button key={p.name} onClick={()=>go(`realisations/${slug(p.name)}`)}><div><img src={p.image} alt={p.name}/><span>{C[lang].view}</span></div><p>0{i+1} · {p.cat}</p><h2>{p.name}</h2><small>{p.year}</small></button>)}</section></>}
function Gallery({lang,open}:{lang:Lang;open:(n:number)=>void}){return <><PageHero number="01" eyebrow={lang==="fr"?"Galerie":"Gallery"} title={lang==="fr"?"Instants":"Moments"} italic={lang==="fr"?"SŌMA.":"by SŌMA."}/><section className="masonry section-pad">{gallery.map((img,i)=><button key={img} onClick={()=>open(i)}><img src={img} alt={`SŌMA gallery ${i+1}`} loading={i>3?"lazy":"eager"}/><span>{String(i+1).padStart(2,"0")}</span></button>)}</section></>}
function Lightbox({index,setIndex}:{index:number;setIndex:(n:number|null)=>void}){return <div className="lightbox" role="dialog" aria-modal="true"><button className="lightbox-close" onClick={()=>setIndex(null)}><X/></button><button onClick={()=>setIndex((index-1+gallery.length)%gallery.length)}><ArrowLeft/></button><img src={gallery[index]} alt="Vue agrandie"/><button onClick={()=>setIndex((index+1)%gallery.length)}><ArrowRight/></button><span>{String(index+1).padStart(2,"0")} / {gallery.length}</span></div>}

function JournalStrip({lang,go}:{lang:Lang;go:(s:string)=>void}){return <section className="journal-strip section-pad"><Head label="09 · Journal" title={C[lang].journal}/><div className="post-grid">{posts.map((p,i)=><button key={p.title} onClick={()=>go(`blog/article-${i+1}`)}><img src={p.image} alt=""/><small>{p.cat} · 6 min</small><h3>{p.title}</h3><ArrowUpRight/></button>)}</div></section>}
function Journal({lang,go,detail}:{lang:Lang;go:(s:string)=>void;detail:string}){if(detail){const p=posts[Math.max(0,Number(detail.replace("article-",""))-1)]||posts[0];return <><section className="article-hero"><img src={p.image} alt=""/><div><p>{p.cat} · 6 min</p><h1>{p.title}</h1></div></section><article className="article-body"><p className="lead">{lang==="fr"?"Une expérience réussie commence bien avant l’arrivée du premier invité. Elle naît d’une intention, d’un rythme et de choix invisibles.":"A successful experience begins long before the first guest arrives. It grows from intention, rhythm and invisible choices."}</p><h2>{lang==="fr"?"L’émotion comme point de départ":"Emotion as a starting point"}</h2><p>{lang==="fr"?"Chez SŌMA, chaque décision sert une sensation. La lumière, le son, l’accueil et les temps de respiration construisent ensemble une mémoire collective.":"At SŌMA, every decision serves a feeling. Light, sound, hospitality and pauses work together to build a collective memory."}</p><blockquote>“Chaque détail participe à l’expérience.”</blockquote></article></>}return <><PageHero number="01" eyebrow="Journal" title={lang==="fr"?"Idées, coulisses":"Ideas, behind the scenes"} italic={lang==="fr"?"& inspirations.":"& inspiration."}/><section className="journal-page section-pad">{posts.concat(posts).map((p,i)=><button key={i} onClick={()=>go(`blog/article-${i%3+1}`)}><img src={p.image} alt=""/><div><small>{p.cat} · 6 min</small><h2>{p.title}</h2><p>{lang==="fr"?"Lire l’article":"Read article"} <ArrowUpRight/></p></div></button>)}</section></>}

function Shop({lang,cart,setCart}:{lang:Lang;cart:number;setCart:(n:number)=>void}){const products=[{name:"Bonnet Signature",price:"320 000 GNF",img:I.portraitBlack},{name:"Édition SŌMA No. 01",price:"410 000 GNF",img:I.fashionClose},{name:"Bonnets Land Classic",price:"280 000 GNF",img:I.portraitWhite}];return <><PageHero number="01" eyebrow="Bonnets Land" title={lang==="fr"?"Objets choisis,":"Selected objects,"} italic={lang==="fr"?"allure libre.":"effortless style."}/><section className="shop-grid section-pad">{products.map((p,i)=><article key={p.name}><div><img src={p.img} alt={p.name}/><span>{i===1?"Édition limitée":"Signature"}</span></div><h2>{p.name}</h2><p>{p.price}</p><button className="btn btn-dark" onClick={()=>setCart(cart+1)}>{lang==="fr"?"Ajouter au panier":"Add to bag"}<Plus size={16}/></button></article>)}</section>{cart>0&&<div className="cart-toast"><ShoppingBag/><span>{cart} {lang==="fr"?"article(s) dans votre panier":"item(s) in your bag"}</span><button onClick={()=>setCart(Math.max(0,cart-1))}><Minus/></button></div>}</>}
const faqFr=[["Quels types d’événements organisez-vous ?","Des événements privés, corporate, célébrations, activations de marque et concepts signature, toujours adaptés à votre intention."],["Intervenez-vous uniquement à Conakry ?","Nous sommes basés à Conakry et pouvons étudier des projets partout en Guinée ainsi qu’à l’international."],["Combien de temps à l’avance faut-il réserver ?","Idéalement de 6 à 16 semaines selon l’ampleur du projet."],["Proposez-vous la décoration ?","Oui. Nous concevons la direction artistique, le décor et la scénographie."],["Peut-on réserver uniquement certains services ?","Oui. Notre accompagnement peut être global ou ciblé."],["Comment demander un devis ?","Utilisez le formulaire de contact ou la réservation guidée."],["Comment fonctionnent les paiements ?","Un acompte confirme la prestation. L’échéancier dépend ensuite du projet."]];
function Faq({lang,go}:{lang:Lang;go:(s:string)=>void}){const qEn=["What kind of events do you produce?","Do you only work in Conakry?","How far ahead should I book?","Do you provide décor?","Can I book selected services only?","How do I request a quote?","How do payments work?"];return <><PageHero number="01" eyebrow="FAQ" title={lang==="fr"?"Avant de":"Before we"} italic={lang==="fr"?"commencer.":"begin."}/><section className="faq-wrap section-pad">{faqFr.map(([q,a],i)=><details key={q}><summary><span><small>0{i+1}</small>{lang==="fr"?q:qEn[i]}</span><Plus/></summary><p>{a}</p></details>)}</section><FinalCta lang={lang} go={go}/></>}
function Contact({lang}:{lang:Lang}){const[sent,setSent]=useState(false);return <><PageHero number="01" eyebrow="Contact" title={lang==="fr"?"Parlons de":"Let’s discuss"} italic={lang==="fr"?"votre idée.":"your idea."}/><section className="contact-layout section-pad"><div className="contact-details"><p>{lang==="fr"?"Une occasion, une marque, une intention ? Écrivez-nous. Nous prendrons le temps de comprendre ce que vous souhaitez faire vivre.":"An occasion, a brand, an intention? Write to us. We’ll take time to understand what you want people to experience."}</p><a href="mailto:soumahcatherine@gmail.com">soumahcatherine@gmail.com</a><a href="https://wa.me/224620327391">+224 620 327 391</a><span>Conakry, Guinée</span></div><form className="contact-form" onSubmit={e=>{e.preventDefault();setSent(true)}}>{["Nom","Entreprise","Email","WhatsApp"].map(x=><label key={x}>{x}<input required={x==="Nom"||x==="Email"} type={x==="Email"?"email":"text"}/></label>)}<label>Service<select><option>Direction artistique</option><option>Organisation événementielle</option><option>SŌMA Bar</option><option>Photographie</option></select></label><label>{lang==="fr"?"Budget estimatif":"Estimated budget"}<select><option>{lang==="fr"?"À définir":"To be defined"}</option><option>5–15 M GNF</option><option>15–50 M GNF</option><option>50 M+ GNF</option></select></label><label className="full">Message<textarea rows={5} required/></label><button className="btn btn-dark full" type="submit">{sent?(lang==="fr"?"Demande envoyée":"Request sent"):(lang==="fr"?"Envoyer la demande":"Send request")} {sent?<Check/>:<ArrowUpRight/>}</button></form></section></>}

function Booking({lang}:{lang:Lang}){const[step,setStep]=useState(1),[choice,setChoice]=useState<Record<string,string>>({}),types=lang==="fr"?["Événement privé","Événement corporate","Activation de marque","Shooting","Prestation bar","Autre projet"]:["Private event","Corporate event","Brand activation","Shoot","Bar service","Other project"];return <section className="booking"><div className="booking-aside"><button onClick={()=>history.back()}><ArrowLeft/> {lang==="fr"?"Retour":"Back"}</button><div><p>SŌMA EXPERIENCES</p><h1>{lang==="fr"?"Commençons par votre intention.":"Let’s begin with your intention."}</h1></div><span>Conakry · Guinée</span></div><div className="booking-main"><div className="booking-progress"><span>{String(step).padStart(2,"0")} / 06</span><div><i style={{width:`${step/6*100}%`}}/></div></div>{step===1&&<Choice title={lang==="fr"?"Quel univers vous intéresse ?":"Which world interests you?"} items={worlds.map(w=>w.name)} value={choice.world} select={v=>setChoice({...choice,world:v})}/>} {step===2&&<Choice title={lang==="fr"?"Quel type de prestation ?":"What kind of service?"} items={types} value={choice.type} select={v=>setChoice({...choice,type:v})}/>} {step===3&&<Step n="03" title={lang==="fr"?"Quand aura lieu votre projet ?":"When will your project take place?"}><label className="date-field"><input type="date" onChange={e=>setChoice({...choice,date:e.target.value})}/></label></Step>} {step===4&&<Step n="04" title={lang==="fr"?"Comment pouvons-nous vous joindre ?":"How can we reach you?"}><div className="booking-fields"><input placeholder={lang==="fr"?"Votre nom":"Your name"}/><input placeholder="Email" type="email"/><input placeholder="WhatsApp"/><textarea placeholder={lang==="fr"?"Parlez-nous de votre idée…":"Tell us about your idea…"}/></div></Step>} {step===5&&<Step n="05" title={lang==="fr"?"Votre demande, en un regard.":"Your request, at a glance."}><dl><div><dt>Univers</dt><dd>{choice.world||"—"}</dd></div><div><dt>Service</dt><dd>{choice.type||"—"}</dd></div><div><dt>Date</dt><dd>{choice.date||"À définir"}</dd></div></dl></Step>} {step===6&&<div className="booking-step success"><span><Check/></span><h2>{lang==="fr"?"Votre demande est prête.":"Your request is ready."}</h2><p>{lang==="fr"?"Merci. L’équipe SŌMA vous contactera pour affiner votre projet.":"Thank you. The SŌMA team will contact you to refine your project."}</p></div>}<div className="booking-controls">{step>1&&step<6?<button onClick={()=>setStep(step-1)}><ArrowLeft/>{lang==="fr"?"Précédent":"Previous"}</button>:<span/>}{step<6&&<button className="btn btn-dark" onClick={()=>setStep(step+1)}>{step===5?(lang==="fr"?"Envoyer":"Send"):(lang==="fr"?"Continuer":"Continue")}<ArrowRight/></button>}</div></div></section>}
function Choice({title,items,value,select}:{title:string;items:string[];value?:string;select:(s:string)=>void}){return <Step n="Choix" title={title}><div className="choice-grid">{items.map((x,i)=><button className={value===x?"selected":""} key={x} onClick={()=>select(x)}><span>0{i+1}</span>{x}{value===x&&<Check/>}</button>)}</div></Step>}
function Step({n,title,children}:{n:string;title:string;children:React.ReactNode}){return <div className="booking-step"><p>{n}</p><h2>{title}</h2>{children}</div>}

function FinalCta({lang,go}:{lang:Lang;go:(s:string)=>void}){const t=C[lang];return <section className="final-cta"><img src={I.toast} alt="Des invités portent un toast"/><div className="hero-shade"/><div><p>{t.finalA}</p><h2>{t.finalB}</h2><button className="btn btn-light" onClick={()=>go("contact")}>{t.talk}<ArrowUpRight/></button></div></section>}
function Footer({lang,go}:{lang:Lang;go:(s:string)=>void}){const t=C[lang];return <footer><div className="footer-top"><div><img src={A("/images/logo-horizontal.png")} alt="SŌMA Experiences"/><p>{lang==="fr"?"Chaque détail participe à l’expérience.":"Every detail shapes the experience."}</p></div><div><p>Explorer</p>{Object.entries(t.nav).slice(1,6).map(([s,n])=><button key={s} onClick={()=>go(s)}>{n}</button>)}</div><div><p>Contact</p><a href="mailto:soumahcatherine@gmail.com">Email</a><a href="https://wa.me/224620327391">WhatsApp</a><span>Conakry, Guinée</span></div></div><div className="newsletter"><label>{t.newsletter}<span><input type="email" placeholder="Email"/><button>{t.subscribe}<ArrowRight/></button></span></label></div><div className="footer-bottom"><span>© 2026 SŌMA Experiences</span><span>FR · EN</span><span>Instagram · TikTok</span></div></footer>}
function slug(s:string){return s.toLowerCase().replaceAll(" ","-")}
